### PR TITLE
use Chrome for travis

### PR DESCRIPTION
**Pull request by Daniel-Xu**
Fixes https://github.com/DockYard/ember-cli-test-interactions/issues/11
Fixes https://github.com/DockYard/ember-cli-test-interactions/pull/3
- remove testem.json
- modify travis.yml
- modify testem.js

### CODE REVIEW

**Comment by Daniel-Xu** [comment]
and we can close this PR? https://github.com/DockYard/ember-cli-test-interactions/pull/3

**Comment by michaeldupuisjr** [comment]
@Daniel-Xu Yep. Any commits that resolve a GH Issue should reference that issue in the commit message:

In this case:

```
Fixes #11
Fixes #3
```

**Comment by michaeldupuisjr** [comment]
Once the commit message is updated, this looks good to me!

**Comment by Daniel-Xu** [comment]
@michaeldupuisjr  thanks for reviewing, I've updated the commit message

**Pull request merged**
